%YAML 1.2
---
# Defaults for the laser
tsl-710:
  wavelength: 1520 nm
  start_wavelength: 1492 nm
  stop_wavelength: 1548 nm
  power: 1 mW
  speed: 1 nm/s
  steps: 100
  step: 1 nm
  interval_trigger: 0.001 nm
  wait_time: 500 ms
  step_time: 0.1 s
  number_sweeps: 1
  sweep_mode: ContOne
  trigger: False
  LD_current: True
  auto_power: False
  coherent_control: True
  fine_tune: False
  shutter: False
  trigger: False
