%YAML 1.2
---
# Configure the devices relevant to the experiment

TSL-710:
  type: scan laser
  name: Santec Laser
  driver: controller.santec.tsl710/tsl710 # last one is the name of the class inside the file.
  connection:
    type: GPIB
    port: 1
  #defaults: config/devices_defaults.yml

PhotoDiode1:
  name: Photodiode 1
  port: 1
  type: analog
  mode: input
  description: Forward Intensity
  calibration:
    units: V
    slope: 1
    offset: 0
  limits:
    min: -2.5
    max: 2.5
  connection:
    type: daq
    device: NI-DAQ

PhotoDiode2:
  name: Photodiode 2
  port: 2
  type: analog
  mode: input
  description: Forward Intensity
  calibration:
    units: V
    slope: 1
    offset: 0
  limits:
    min: -2.5
    max: 2.5
  connection:
    type: daq
    device: NI-DAQ

Stage1:
  name: Stage 1
  type: analog
  mode: output
  description: X Direction
  port: 1
  calibration: # Convert Volts into device units
    units: um
    slope: 10
    offset: 0
  limits:
    min: 0
    max: 100
  connection:
    type: daq
    device: NI-DAQ

NI-DAQ:
  name: NI-DAQ
  type: daq
  model: ni
  number: 2
  driver: pharos.model.daq.ni/ni
  connection:
    type: daq
    port: 2
  trigger: external
  trigger_source: PFI0

oscilloscope:
  type: daq
  driver: model.daq.keysight
  name: Keysight oscilloscope
  connection:
    type: USB
    port: 1

DummyDaq:
  type: daq
  name: dummy daq
  driver: pharos.model.daq.daqDummy/dummyDaq
  connection:
    type: daq
    port: 1
  defaults: config/devices_defaults.yml
  trigger: external
  trigger_source: PFI0




