%YAML 1.2
---
# Define and Configure the devices relevant to the experiment

TSL-710:
  type: scan laser
  name: Santec Laser
  driver: controller.santec.tsl710/tsl710 # last one is the name of the class inside the file.
  connection:
    type: GPIB
    port: 1
  defaults: config/devices_defaults.yml #setting defaults will trigger an action after initializing each device with model/lib/device.py class
  outputs:
    - time

ThorRotation1:
  type: Rotation Stage
  name: Rotation 1
  driver: controller.thorlabs.tdc001/TDC
  description: Laser Power 1
  connection:
    type: daq  # Even if it is not a DAQ, it initializes the driver correctly.
    port: 83860737
  outputs:
    - position

PhotoDiode1:
  name: Photodiode Test
  port: 1
  type: analog
  mode: input
  description: Forward Intensity
  calibration:
    units: V
    slope: 1
    offset: 0
  limits:
    min: -10.0
    max: 10
  connection:
    type: daq
    device: NI-DAQ

PhotoDiode3:
  name: Photodiode Test 2
  port: 3
  type: analog
  mode: input
  description: Forward Intensity
  calibration:
    units: V
    slope: 1
    offset: 0
  limits:
    min: -10.0
    max: 10
  connection:
    type: daq
    device: NI-DAQ


PhotoDiode4:
  name: Photodiode Test 4
  port: 4
  type: analog
  mode: input
  description: Forward Intensity
  calibration:
    units: V
    slope: 1
    offset: 0
  limits:
    min: -10.0
    max: 10
  connection:
    type: daq
    device: NI-DAQ

PhotoDiode2:
  name: Photodiode 2
  port: 2
  type: analog
  mode: input
  description: Forward Intensity
  calibration:
    units: V
    slope: 1
    offset: 0
  limits:
    min: -2.5
    max: 2.5
  connection:
    type: daq
    device: NI-DAQ

NI-DAQ:
  name: NI-DAQ
  type: daq
  model: ni
  number: 2
  driver: pharos.model.daq.ni/ni
  connection:
    type: daq
    port: 2
  trigger: external
  trigger_source: PFI0