%YAML 1.2
---
# Defaults for the laser
Santec Laser:
  wavelength: 1520 nm
  start_wavelength: 1492 nm
  stop_wavelength: 1548 nm
  power: 1 mW
  speed: 1 nm/s
  steps: 100
  step: 1 nm
  interval_trigger: 0.001 nm
  wait_time: 0 ms
  step_time: 0.1 s
  number_sweeps: 1
  sweep_mode: ContOne
  sweep: continuous
  mode: one
  trigger: False
  LD_current: True
  auto_power: False
  coherent_control: False
  fine_tune: False
  shutter: True
  trigger: False

dummy daq:
  test_value: 1