%YAML 1.2
---
# Configures the steps of an experiment


init:
  devices: 'config/devices.yml'

scan:
  axis:
    name:
      type: variable
      range: [10, 20, .1]
    time:
      repetitions: 20

finish:
  TSL-10:
    shutter: False