%YAML 1.2
---
# Configures the steps of an experiment

init:
  tsl-710:
    file: 'config/defaults.yml'

  detectors:
    NI-DAQ:
      Photodiode 1
    oscilloscope:
      New Signal
scan:
  axis:
    name:
      type: variable
      range: [10, 20, .1]
    time:
      repetitions: 20

finish:
  TSL-10:
    shutter: False