%YAML 1.2
---
# Configures the steps of an experiment

init:
  devices: 'config/devices.yml'
  default_directory: 'F:\Data'

monitor:
  laser:
    name: Santec Laser
    params:
      start_wavelength: 1491 nm
      stop_wavelength:  1510 nm
      wavelength_speed:  10 nm/s
      interval_trigger: 0.1 nm
      sweep_mode: ContOne
      wavelength_sweeps: 1
      timing_trigger: Step  # Options are Start/Stop/Step/None. See manual for references
  detectors:
  - OOPScattering
  - Acetylene
  - Cyanide
  - Transmission
  - Reflection
  daq:
    trigger: external # external/internal
    trigger_source: PFI0 # trigger port used for each analog to digital conversion
    start_source: '' # trigger port used for starting the measurement
    
scan:
  laser:
    name: Santec Laser
    params:
      start_wavelength: 1526 nm
      stop_wavelength:  1526.1 nm
      wavelength_speed:  1 nm/s
      interval_trigger: 0.001 nm
      sweep_mode: ContOne
      wavelength_sweeps: 1
      timing_trigger: Step  # Options are Start/Stop/Step/None. See manual for references
  axis:  # The laser doesn't need to appear here, it is always considered the first axis of the scan
    device:
      name: Rotation 1
      range: [35deg, 35deg, 1.0deg]
      property: position
  shutter:
    port: PFI1
    delay: 20ms
  switch:
    port: PFI3
  detectors:
    - OOPScattering
    - Acetylene
    - Cyanide
    - Transmission
    - Reflection
  daq:
    trigger: external # external/internal
    trigger_source: PFI0 # trigger port used for each analog to digital conversion
    start_source: '' # trigger port used for starting the measurement
    
finish:
  TSL-10:
    shutter: False