# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\laserwidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(372, 747)
        self.gridLayout_4 = QtGui.QGridLayout(Form)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.wavelength_line = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.wavelength_line.setFont(font)
        self.wavelength_line.setObjectName(_fromUtf8("wavelength_line"))
        self.gridLayout_4.addWidget(self.wavelength_line, 0, 1, 1, 2)
        self.verticalSlider = QtGui.QSlider(Form)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.gridLayout_4.addWidget(self.verticalSlider, 0, 4, 9, 2)
        self.label_2 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.start_line = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.start_line.setFont(font)
        self.start_line.setObjectName(_fromUtf8("start_line"))
        self.gridLayout_4.addWidget(self.start_line, 1, 1, 1, 2)
        self.label_7 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 6, 1, 1)
        self.label_3 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.stop_line = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.stop_line.setFont(font)
        self.stop_line.setObjectName(_fromUtf8("stop_line"))
        self.gridLayout_4.addWidget(self.stop_line, 2, 1, 1, 2)
        self.lineEdit = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_4.addWidget(self.lineEdit, 2, 6, 1, 1)
        self.label_4 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.speed_line = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.speed_line.setFont(font)
        self.speed_line.setObjectName(_fromUtf8("speed_line"))
        self.gridLayout_4.addWidget(self.speed_line, 3, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 3, 3, 1, 1)
        self.label_6 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 4, 0, 1, 1)
        self.speed_line_2 = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.speed_line_2.setFont(font)
        self.speed_line_2.setObjectName(_fromUtf8("speed_line_2"))
        self.gridLayout_4.addWidget(self.speed_line_2, 4, 1, 1, 2)
        self.label_11 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 5, 0, 1, 1)
        self.speed_line_6 = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.speed_line_6.setFont(font)
        self.speed_line_6.setText(_fromUtf8(""))
        self.speed_line_6.setObjectName(_fromUtf8("speed_line_6"))
        self.gridLayout_4.addWidget(self.speed_line_6, 5, 1, 1, 2)
        self.label_8 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 6, 0, 1, 1)
        self.speed_line_3 = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.speed_line_3.setFont(font)
        self.speed_line_3.setObjectName(_fromUtf8("speed_line_3"))
        self.gridLayout_4.addWidget(self.speed_line_3, 6, 1, 1, 2)
        self.label_9 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 7, 0, 1, 1)
        self.speed_line_4 = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.speed_line_4.setFont(font)
        self.speed_line_4.setObjectName(_fromUtf8("speed_line_4"))
        self.gridLayout_4.addWidget(self.speed_line_4, 7, 1, 1, 2)
        self.label_10 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 8, 0, 1, 1)
        self.speed_line_5 = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.speed_line_5.setFont(font)
        self.speed_line_5.setObjectName(_fromUtf8("speed_line_5"))
        self.gridLayout_4.addWidget(self.speed_line_5, 8, 1, 1, 2)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout.addWidget(self.radioButton_2, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 9, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.gridLayout_2.addWidget(self.radioButton_3, 0, 0, 1, 1)
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.gridLayout_2.addWidget(self.radioButton_4, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 9, 2, 1, 3)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_3.addWidget(self.checkBox, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 9, 5, 1, 2)
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_4.addWidget(self.pushButton, 10, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(Form)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_4.addWidget(self.pushButton_2, 10, 1, 1, 2)
        self.pushButton_5 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_4.addWidget(self.pushButton_5, 10, 5, 2, 2)
        self.pushButton_3 = QtGui.QPushButton(Form)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_4.addWidget(self.pushButton_3, 11, 0, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(Form)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_4.addWidget(self.pushButton_4, 11, 1, 1, 2)
        self.pushButton_6 = QtGui.QPushButton(Form)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_4.addWidget(self.pushButton_6, 12, 0, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(Form)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_4.addWidget(self.pushButton_7, 12, 1, 1, 2)
        self.label_5 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 13, 0, 1, 3)
        self.label.setBuddy(self.wavelength_line)
        self.label_2.setBuddy(self.start_line)
        self.label_7.setBuddy(self.lineEdit)
        self.label_3.setBuddy(self.stop_line)
        self.label_4.setBuddy(self.speed_line)
        self.label_6.setBuddy(self.speed_line_2)
        self.label_11.setBuddy(self.speed_line_2)
        self.label_8.setBuddy(self.speed_line_2)
        self.label_9.setBuddy(self.speed_line_2)
        self.label_10.setBuddy(self.speed_line_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.wavelength_line, self.start_line)
        Form.setTabOrder(self.start_line, self.stop_line)
        Form.setTabOrder(self.stop_line, self.speed_line)
        Form.setTabOrder(self.speed_line, self.speed_line_2)
        Form.setTabOrder(self.speed_line_2, self.speed_line_6)
        Form.setTabOrder(self.speed_line_6, self.speed_line_3)
        Form.setTabOrder(self.speed_line_3, self.speed_line_4)
        Form.setTabOrder(self.speed_line_4, self.speed_line_5)
        Form.setTabOrder(self.speed_line_5, self.verticalSlider)
        Form.setTabOrder(self.verticalSlider, self.lineEdit)
        Form.setTabOrder(self.lineEdit, self.radioButton)
        Form.setTabOrder(self.radioButton, self.radioButton_2)
        Form.setTabOrder(self.radioButton_2, self.radioButton_3)
        Form.setTabOrder(self.radioButton_3, self.radioButton_4)
        Form.setTabOrder(self.radioButton_4, self.checkBox)
        Form.setTabOrder(self.checkBox, self.pushButton)
        Form.setTabOrder(self.pushButton, self.pushButton_3)
        Form.setTabOrder(self.pushButton_3, self.pushButton_6)
        Form.setTabOrder(self.pushButton_6, self.pushButton_2)
        Form.setTabOrder(self.pushButton_2, self.pushButton_4)
        Form.setTabOrder(self.pushButton_4, self.pushButton_7)
        Form.setTabOrder(self.pushButton_7, self.pushButton_5)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "Wavelength", None))
        self.label_2.setText(_translate("Form", "Start", None))
        self.label_7.setText(_translate("Form", "Power", None))
        self.label_3.setText(_translate("Form", "Stop", None))
        self.label_4.setText(_translate("Form", "Speed", None))
        self.label_6.setText(_translate("Form", "# Steps", None))
        self.label_11.setText(_translate("Form", "Step", None))
        self.label_8.setText(_translate("Form", "Wait Time", None))
        self.label_9.setText(_translate("Form", "Step Time", None))
        self.label_10.setText(_translate("Form", "# Sweeps", None))
        self.groupBox.setTitle(_translate("Form", "Sweep", None))
        self.radioButton.setText(_translate("Form", "Continuous", None))
        self.radioButton_2.setText(_translate("Form", "Step", None))
        self.groupBox_2.setTitle(_translate("Form", "Mode", None))
        self.radioButton_3.setText(_translate("Form", "One-way", None))
        self.radioButton_4.setText(_translate("Form", "Two-way", None))
        self.groupBox_3.setTitle(_translate("Form", "Trigger", None))
        self.checkBox.setText(_translate("Form", "Ext. Trigger", None))
        self.pushButton.setText(_translate("Form", "LD Current", None))
        self.pushButton_2.setText(_translate("Form", "Fine Tune", None))
        self.pushButton_5.setText(_translate("Form", "Start", None))
        self.pushButton_3.setText(_translate("Form", "Auto Power", None))
        self.pushButton_4.setText(_translate("Form", "Shutter", None))
        self.pushButton_6.setText(_translate("Form", "Coherent", None))
        self.pushButton_7.setText(_translate("Form", "Trigger", None))
        self.label_5.setText(_translate("Form", "Current condition:", None))

