# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\laserwidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(537, 503)
        self.gridLayout_4 = QtGui.QGridLayout(Form)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.wavelength_line = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.wavelength_line.setFont(font)
        self.wavelength_line.setObjectName(_fromUtf8("wavelength_line"))
        self.gridLayout_4.addWidget(self.wavelength_line, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.start_wavelength_line = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.start_wavelength_line.setFont(font)
        self.start_wavelength_line.setObjectName(_fromUtf8("start_wavelength_line"))
        self.gridLayout_4.addWidget(self.start_wavelength_line, 1, 1, 1, 2)
        self.label_7 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 5, 1, 1)
        self.label_3 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.stop_wavelength_line = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.stop_wavelength_line.setFont(font)
        self.stop_wavelength_line.setObjectName(_fromUtf8("stop_wavelength_line"))
        self.gridLayout_4.addWidget(self.stop_wavelength_line, 2, 1, 1, 2)
        self.power_line = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.power_line.setFont(font)
        self.power_line.setObjectName(_fromUtf8("power_line"))
        self.gridLayout_4.addWidget(self.power_line, 2, 5, 1, 1)
        self.label_4 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.speed_line = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.speed_line.setFont(font)
        self.speed_line.setObjectName(_fromUtf8("speed_line"))
        self.gridLayout_4.addWidget(self.speed_line, 3, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 3, 3, 1, 1)
        self.label_6 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 4, 0, 1, 1)
        self.steps_line = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.steps_line.setFont(font)
        self.steps_line.setObjectName(_fromUtf8("steps_line"))
        self.gridLayout_4.addWidget(self.steps_line, 4, 1, 1, 2)
        self.label_11 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 5, 0, 1, 1)
        self.step_line = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.step_line.setFont(font)
        self.step_line.setText(_fromUtf8(""))
        self.step_line.setObjectName(_fromUtf8("step_line"))
        self.gridLayout_4.addWidget(self.step_line, 5, 1, 1, 2)
        self.label_8 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 6, 0, 1, 1)
        self.wait_line = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.wait_line.setFont(font)
        self.wait_line.setObjectName(_fromUtf8("wait_line"))
        self.gridLayout_4.addWidget(self.wait_line, 6, 1, 1, 2)
        self.label_9 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 7, 0, 1, 1)
        self.step_time_line = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.step_time_line.setFont(font)
        self.step_time_line.setObjectName(_fromUtf8("step_time_line"))
        self.gridLayout_4.addWidget(self.step_time_line, 7, 1, 1, 2)
        self.label_10 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 8, 0, 1, 1)
        self.sweeps_line = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sweeps_line.setFont(font)
        self.sweeps_line.setObjectName(_fromUtf8("sweeps_line"))
        self.gridLayout_4.addWidget(self.sweeps_line, 8, 1, 1, 2)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.continuous_button = QtGui.QRadioButton(self.groupBox)
        self.continuous_button.setObjectName(_fromUtf8("continuous_button"))
        self.gridLayout.addWidget(self.continuous_button, 0, 0, 1, 1)
        self.step_button = QtGui.QRadioButton(self.groupBox)
        self.step_button.setObjectName(_fromUtf8("step_button"))
        self.gridLayout.addWidget(self.step_button, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 9, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.one_button = QtGui.QRadioButton(self.groupBox_2)
        self.one_button.setObjectName(_fromUtf8("one_button"))
        self.gridLayout_2.addWidget(self.one_button, 0, 0, 1, 1)
        self.two_button = QtGui.QRadioButton(self.groupBox_2)
        self.two_button.setObjectName(_fromUtf8("two_button"))
        self.gridLayout_2.addWidget(self.two_button, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 9, 2, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.trigger_check = QtGui.QCheckBox(self.groupBox_3)
        self.trigger_check.setObjectName(_fromUtf8("trigger_check"))
        self.gridLayout_3.addWidget(self.trigger_check, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 9, 4, 1, 2)
        self.LD_button = QtGui.QPushButton(Form)
        self.LD_button.setObjectName(_fromUtf8("LD_button"))
        self.gridLayout_4.addWidget(self.LD_button, 10, 0, 1, 1)
        self.fine_tune_button = QtGui.QPushButton(Form)
        self.fine_tune_button.setObjectName(_fromUtf8("fine_tune_button"))
        self.gridLayout_4.addWidget(self.fine_tune_button, 10, 1, 1, 1)
        self.start_button = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.start_button.setFont(font)
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.gridLayout_4.addWidget(self.start_button, 10, 4, 2, 2)
        self.auto_power_button = QtGui.QPushButton(Form)
        self.auto_power_button.setObjectName(_fromUtf8("auto_power_button"))
        self.gridLayout_4.addWidget(self.auto_power_button, 11, 0, 1, 1)
        self.shutter_button = QtGui.QPushButton(Form)
        self.shutter_button.setObjectName(_fromUtf8("shutter_button"))
        self.gridLayout_4.addWidget(self.shutter_button, 11, 1, 1, 1)
        self.coherent_button = QtGui.QPushButton(Form)
        self.coherent_button.setObjectName(_fromUtf8("coherent_button"))
        self.gridLayout_4.addWidget(self.coherent_button, 12, 0, 1, 1)
        self.trigger_output_button = QtGui.QPushButton(Form)
        self.trigger_output_button.setObjectName(_fromUtf8("trigger_output_button"))
        self.gridLayout_4.addWidget(self.trigger_output_button, 12, 1, 1, 1)
        self.stop_button = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.stop_button.setFont(font)
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.gridLayout_4.addWidget(self.stop_button, 12, 4, 1, 2)
        self.condition_label = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.condition_label.setFont(font)
        self.condition_label.setObjectName(_fromUtf8("condition_label"))
        self.gridLayout_4.addWidget(self.condition_label, 13, 0, 1, 2)
        self.power_slider = QtGui.QSlider(Form)
        self.power_slider.setMinimum(1)
        self.power_slider.setMaximum(10000)
        self.power_slider.setOrientation(QtCore.Qt.Vertical)
        self.power_slider.setObjectName(_fromUtf8("power_slider"))
        self.gridLayout_4.addWidget(self.power_slider, 0, 4, 9, 1)
        self.label.setBuddy(self.wavelength_line)
        self.label_2.setBuddy(self.start_wavelength_line)
        self.label_7.setBuddy(self.power_line)
        self.label_3.setBuddy(self.stop_wavelength_line)
        self.label_4.setBuddy(self.speed_line)
        self.label_6.setBuddy(self.steps_line)
        self.label_11.setBuddy(self.steps_line)
        self.label_8.setBuddy(self.steps_line)
        self.label_9.setBuddy(self.steps_line)
        self.label_10.setBuddy(self.steps_line)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.wavelength_line, self.start_wavelength_line)
        Form.setTabOrder(self.start_wavelength_line, self.stop_wavelength_line)
        Form.setTabOrder(self.stop_wavelength_line, self.speed_line)
        Form.setTabOrder(self.speed_line, self.steps_line)
        Form.setTabOrder(self.steps_line, self.step_line)
        Form.setTabOrder(self.step_line, self.wait_line)
        Form.setTabOrder(self.wait_line, self.step_time_line)
        Form.setTabOrder(self.step_time_line, self.sweeps_line)
        Form.setTabOrder(self.sweeps_line, self.power_line)
        Form.setTabOrder(self.power_line, self.continuous_button)
        Form.setTabOrder(self.continuous_button, self.step_button)
        Form.setTabOrder(self.step_button, self.one_button)
        Form.setTabOrder(self.one_button, self.two_button)
        Form.setTabOrder(self.two_button, self.trigger_check)
        Form.setTabOrder(self.trigger_check, self.LD_button)
        Form.setTabOrder(self.LD_button, self.auto_power_button)
        Form.setTabOrder(self.auto_power_button, self.coherent_button)
        Form.setTabOrder(self.coherent_button, self.fine_tune_button)
        Form.setTabOrder(self.fine_tune_button, self.shutter_button)
        Form.setTabOrder(self.shutter_button, self.trigger_output_button)
        Form.setTabOrder(self.trigger_output_button, self.start_button)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "Wavelength", None))
        self.label_2.setText(_translate("Form", "Start", None))
        self.label_7.setText(_translate("Form", "Power", None))
        self.label_3.setText(_translate("Form", "Stop", None))
        self.label_4.setText(_translate("Form", "Speed", None))
        self.label_6.setText(_translate("Form", "# Steps", None))
        self.label_11.setText(_translate("Form", "Step", None))
        self.label_8.setText(_translate("Form", "Wait Time", None))
        self.label_9.setText(_translate("Form", "Step Time", None))
        self.label_10.setText(_translate("Form", "# Sweeps", None))
        self.groupBox.setTitle(_translate("Form", "Sweep", None))
        self.continuous_button.setText(_translate("Form", "Continuous", None))
        self.step_button.setText(_translate("Form", "Step", None))
        self.groupBox_2.setTitle(_translate("Form", "Mode", None))
        self.one_button.setText(_translate("Form", "One-way", None))
        self.two_button.setText(_translate("Form", "Two-way", None))
        self.groupBox_3.setTitle(_translate("Form", "Trigger", None))
        self.trigger_check.setText(_translate("Form", "Ext. Trigger", None))
        self.LD_button.setText(_translate("Form", "LD Current", None))
        self.fine_tune_button.setText(_translate("Form", "Fine Tune", None))
        self.start_button.setText(_translate("Form", "Start", None))
        self.auto_power_button.setText(_translate("Form", "Auto Power", None))
        self.shutter_button.setText(_translate("Form", "Shutter", None))
        self.coherent_button.setText(_translate("Form", "Coherent", None))
        self.trigger_output_button.setText(_translate("Form", "Trigger", None))
        self.stop_button.setText(_translate("Form", "Stop", None))
        self.condition_label.setText(_translate("Form", "Current condition:", None))

